[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "1176092ac93b7833cea4e3fa69d6a9777da68b59"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "38c6f57f5cfc83cf88e152a038bf209dfdd31872e79380b73482bf17243b794f"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "0198d4d8e8a0815fd7676843bdd820f0cc8a250e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "f0f37b3be5193fb333bf4de401863ba976af937a399c7e9fe90681349f0557bc"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "b91aebb543432814bb74dac8cbf53da5dd2cab25"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "d37d9c96b9286ec67155fdd9ffc5af11b18a9501fbac2201787f294190ca9cdb"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "57589e83fd66d0f293e81e21c65858eb234e0b77"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "c1aa82833fdf82dd85968fa06a7f2d540cae91746f4bb13a460bee24f13ccebf"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "3f45bee786fdc03e31512a69e82c957c92e2ac27"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "367648f4eabe6e7186e31ed854a8f5a91de769185a1b119ad41b51cd4be40714"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "758d9d7286db0745fcc98e0c508ab00a2ef8f487"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "15424df064f18c6ee001538013a74bfa1b00622dc0eb9bf7a22a6a241cd95164"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "22845b7ab39ea8f01f72147fbcd6a57542ef53bb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "799dec6bf2bf776a1977fdb0c9fc298a4cf56be862e12fcd3393e4c2162a2b1b"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "f9d32dfa3ddbe6502b3cc5338b5fde04b1b39505"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "f5aba36342c9849782fc817804ba03ec308cc2fe63b12a99dc9a996dab886cf3"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "1e43c10d28354abc88d76b70f2bca6a6a4affc00"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "1d5a33b1f6ee17d0a20e4959ec6a5c1b6328e789ce98f83f28870f85cfd37457"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "e0877c631ccc7ef85e6f20c2ac32907b6192f043"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "2cb25d88352f9718b6dc82b77a575af4e118651f6cb93da571dbba3d167d78e1"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "1492e893bdeeef9a000422493254265a6d010736"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "3fbd5ec4ad482b3e591879e34780caad6609d6c86a16d5666a1084e3c0b084fc"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "94873893d27e50d891f24959c0b7db579d627423"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "a5769e079d5208e813e40eb2f351fdbfa6bdc0659e614ee32af677652e9a9fbd"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "03b425ea14776b851a9d136f4df5c87d742b005d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "f22af7cd9aec700d987e7a0c062ab510d61d632b992196e847dc84c21e9ae228"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-gnu-libgfortran3.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "66e1802dc48dbf8f22ea30a2c0fcea00ebd39c33"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "b2d97d4f92b513416ef7771486495f513a1608966431890d18177528f6110fe4"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "47c0554718aa8bbff25b5b0dfe2c40cb2757c837"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "06b14002a2025cc6afc5713c25250a4686039d1086b0c7ea8890bec39d9cdce9"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "2f0f1c3a6c6630ee59b9cc9233fe8e99c234bff1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "c4bcde9dc23117a36b3c177454c9836951299eba21e335fd67d69dc924e7a4df"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-musl-libgfortran3.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "147ca20347e1e2c0cff80f1e4ff7f3e1d41e8008"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "b8a464d3bd2ed2b1d853f3af091168ddbcc9a387ecf89facd5ffa12f36d42cd4"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-musl-libgfortran4.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "fe4c350f2eb4d53f97f27ead03e6f04c37555829"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "ad3af932f0f7f7cf8de5e80d74fd7e92198df654af96e434cdd5ca7ad3a33517"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "bbd37b8c81416e50cd981f59cae10ef023a23955"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "5b1ed3b62cb46fb45742f59c567e521582d93460d5a20771c6d272a3a0a34a39"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "6a0d36fee818dfafd95aa16fd49bfc3fdd288f3e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "2e186cd09ef68c0a724a315f589aefbeeae74b57de360e25f6f45b71688e531e"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "0fe701378e644acd994b0c268c7277a08af7ac21"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "83b82d687cdf283299f29f62aab8f7a1b1882003365a9dcf1df1b2947d1ff061"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "ab77935c35da792016529ce6e5aa2ae817e49401"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FEAST.download]]
    sha256 = "9368a50357d4d50b69b9629a27a7b3bac9ae58c75cfaf5faba0a5b04ce2ed1a0"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "6a362daf39b64e2bb49e883734d8cb3d8b57b394"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FEAST.download]]
    sha256 = "614ee16fe48a95c20ab579fb9b995e7eb9ca461c5b47c606907860c89695bf0e"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "2e956df3ffe6cc3d10fcc087f6008d869ca7f801"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FEAST.download]]
    sha256 = "8942aa25bf0f3f7c840e8f679d76ab23a224a5b15114fbc8f6e0ddc12961cb21"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "347828cf08b4e4427e7d414687845af7481f56db"
libc = "glibc"
os = "linux"

    [[FEAST.download]]
    sha256 = "0aa4d9d17c5ba258e3aafa2b3327628e7a23a7698591b94231dc1b3c5540a80b"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.2+0/FEAST.v4.0.2.x86_64-linux-gnu.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "41977487a7f5455344ed92015fa970c7bd392011"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "a390769a97d70c3dc6746cedf4a91983d2a6a2f50040a20c84168b181ac6a935"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.7+0/FEAST.v4.0.7.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "e339d9f4734514b245d408b26faa354e77478228"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "69f5c263b0d67353cfb316c270203c652ed703b9c443909f1f6fca09be86ee22"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.7+0/FEAST.v4.0.7.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "e3013618de509f959c10f9fcb36e5b0f9542cb5a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "2704a4811837e9652effe6d0479a23669f66aaff8fdb6cc221879eea2e0be4ae"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.7+0/FEAST.v4.0.7.x86_64-linux-gnu-libgfortran5.tar.gz"
