[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "00c2d2bed0585a9acf93aa40ca9730fec70fcf1a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "d0280e74575f64f1c655864d21e5fb560cb3ddb54a1a1ec65f65a95952685789"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "0135c700f79635581385a5de3f76ffa18a65ee1a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "22f28100bdca57f2358c4a2714ef5c1cdb4b58a6cd194aeb0935f263858eeb8b"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "441baccdd87dd22a05409c2756971ec1ceeb645d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "55799ea9b15e5461878da68ddf5d8fdfd5a6ddcaaa53a7f301d848751905a9bc"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "26d93072c4b22c0cdfdb4ce0b3151f6429cdbfa4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "86206684229d3583f3e45b77647aa47ee232a66128aae3166bf41cd564a01ea8"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "ba5c7e2a58ba07b5e72461ba9f20573c111d5c36"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "71edfc5d64ab9b90b5effff0db35b7b89e9ea2a12bb7f926bc8ae27d95e2a37d"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "7aab108e94174ad4f1c085316819b872ddcd1ea0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "397f9af1c847a8e81b1e9cb45bc5c1ff1f7ddaabeffff43408bc012ff3c20392"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "800c89042b75cef205673aca154c72d41d9894b3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "10963ab720b5e09f0cd805d7773374db07966d206baf4398b8ba2a622aa850fa"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "ff2eda3fde0fa22c188bf1c8571e2f1bd8db615e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "8d09f5a02f9164f85c3abd41bc595aac5aedb5f186bec76a8005c519dda6e7e9"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "a3495144a3bdd6024fff5ebb70b9730f667344e2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "f0209ea77682d97ed65d88b65b67aa574342ad19142fe8451eacdbd2b4297aa5"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "994a969d42fdbc9986414422b3f98e9b4a7cba98"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "018772040dd9d4c8b660db62e17cb7863a1c053b017f2582dfa9493a58bcfc36"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "c1f21e704050a43f94a707e0e74ee4e61a02a120"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "a8542862bbc46da2a06bb381ed9d2b16c991dc625be19d046b821b3b791b3cd9"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "9fbdefdb4015039eda88f19128156058cd746d7e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "aa9ad70684178250634ec903a373fdafdb224823813caa9ca539485c38a3f8e7"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "92ea1eab71fb5695cb663fc91b1ff0ee86fd551f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "68d63750d1f762690bc7c0db1b22867f43f25508b29570348247e8fab222aa9f"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-gnu-libgfortran3.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "60a64c744290f1974c9d144b8080b4f5c26b1f09"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "e28d91cf1ad0c4d9425545d1463f3e50f4e1b0b5ab1a71fb401afe850ca52b03"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "c35f66c69598ea403fe446a44fb93561193ac53a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "71c1bf98213ae0dd75050ce8f7f292586ba5076b89ecd42b76c51d996cfa30bc"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "d7f1f537f070821c46a26683fc9344efa492f208"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "5ed7490e14310c8dbd2cb178504294fbf60bbd1834b672450f95b2219649dff6"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-musl-libgfortran3.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "abc8b02d61227a1f72433dee35fb1510694e94bf"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "00cb9943e096d24aa8bc7038711de3b26d6b776a5c28c9fae8f7f91433f96a7f"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-musl-libgfortran4.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "f47d27b4f373dfc625d3ae93cdbde186884cfe34"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "746860053f73ea7b70b55a81ca32181ad4b5fb27d10a314ab47742b010793b26"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "7e1452947e88cc6d2fdf2a72a413dde56847cd42"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "aa3e1410825f8235bacf7006276d7609b03133fc07d7734c014fc915fa0e5ec1"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "a5df4d9e5b5833264f08130c1e3129843c586384"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "eed26ac07f948a0a0299576018eaaac324fe1b4a0afb5b189e245f84db7ab513"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "67fb75376d80161d966ea06336374d5ccb1f370e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "05f77ccf8c57cefebb06f4685eabf143b3af19ef2d5c739d8ab81698551350f4"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "f3fc44e509e673ed14a353e901975ae9060528c4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "3c81558e7675da0dc064bd2c1223635d9f72e002f94a024c04d17163f701ed73"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "6fda0b4cd4c3eab2ab28fcd984cd1717ef09b466"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "88db955adfda58187d0c98d23ba29b47ed7ed6fdd7ff4627e07ce8ae6616bda6"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "cde27e747eda4d3036ae9e8aee5ff780c40d7480"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "a522f0dca4c305fc451d6fa414fd9f35e32fb145b2c2b06cdd047d387bf1e886"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "5bcebe7023aeaf07cceada295d05322117a26d90"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FEAST.download]]
    sha256 = "d27f41f465d72ccbdc28beac3477d25035bd95a02aabd03d2d14b0214a6d6e17"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "e2345858fbe473282610f1440be56d871dd7cb1f"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FEAST.download]]
    sha256 = "18e355e7129f27460ceb50ed68ab15d69985f8ae51f9c4114c6001a94cafa7ff"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "1a65bb2c31ca338be3f655e0c691fea82cee18c8"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FEAST.download]]
    sha256 = "154d77e4d1e19a8995ad009cf0cb554f80e95491e6ce1de1657b79371a4fb8da"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
