[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "a4af543257c7dbbb2e732c411ddce8a561b68ad5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "26c17dc03bb5a75699f5295ecc87086e513636baafc434e32bc82eac90f79ad3"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "3cc244ac4cc09fc926397fb4b2dbcad618c9f0c1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "f751eb5b3cfda6b5692c9725b2a699e449ad37622ce5511348cfd2723007dfbb"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "52caf8a7cc626ac5160f383dac0afb6ab58870f6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "aed50783a8c648e5c15ef8e600f8f916baef737cccc35a74243cc964ca50da77"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "79832869a88d581dec1e00166344fddb0f7e3ae4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "d870f65a3a8bffe673bbf1ff324ff9af3e140c5525db19d313c53eeacfc2b0e7"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "cd6474fcb27ba7254a33e351f964b3b2ecc039cb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "3ac9216e296c8f464e1a7f4e54a3212e00e92c3ad75f02d65cacec88886014c3"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "17cb8a302f65d72fd454a702ee90057d1cf9a4d6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "46326a39792f4118eba0d86fe98c25320bc7dc5991544d748785a574e7ef7448"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "4d4f5fe6b41e5d5203eec7df8c4904e99c5da9d5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "59fbebb01d06489a6ed91fdc9b8f7166b21a1dc3627bcc7dabef477829b4fec4"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "5973155f03a038a14359b6b8424b9d3345c64863"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "f6eda2a3ad5031b4bcc463b1e28a3aa17b4fd5b810b3d158b18e31bbfb8b1fcb"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "014b02b2909424de1d289609a1075b80c95871a0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "546987e90f2897da0f65cd40c1a20f8576922afbd959888d6a13befe0c0edbb6"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "5e1482544f14894ab71506ecf2e2b46ae88dc7c2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "07b43ad1a4fb35f552ff1925fb828980d9e846de57747668e96945ac6ba3ba03"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "09163b02cd59b4f60e8b528bba560ed8109b0827"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "560d2188897a161506cfd688973e89004b163bd4ee04c0b55456a786c21c5236"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "16dcaf97967c4127e9a411b24941b14ae52d8f93"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "f4282f9daf17f2bc81e8079c52f36f1ea26793f55a49c6adda79ca1d1dc98b8f"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "83f93113824b79379b9f35680a1b7b2faeb3d870"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "2cc38bbb01ec0b3161192f9e166e6875bc38fdfb707aab8f7839a9cf3798539a"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-gnu-libgfortran3.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "f06a2d459babc0a3b46cba2fb9d0eea0d03f9ca6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "4462a567cdb410af00ccd219a88b4a5783abdf684de811b17faa504c7553187e"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "34f781fcb203c555622ab9b064e95f3aa77aaef6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "3f4d5684cd72463f110fec986cd4abba691f698a8bd5e2eb62da2842298cd5a8"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "5601b8c74466a245163bc68603d712b819ab5eee"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "cf0656924c81152b0eb856d5f4586ff58fb1baaa61bd3b5925240d7da1999530"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-musl-libgfortran3.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "f2d1cd916e97f72261f61ce34c6853bad228b16d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "4f74eb12fdc2eba731954e0084c9c16f64bf81a663739cb7a4a523908a8f087d"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-musl-libgfortran4.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "64ce763ee77dbffeaaa741f131e9cd57b08fc9cb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "865dab6ba7af2acbe9ae23cec91f7fa3a8cf0394adfec7f159aba189ce4b71d0"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "3a4a156cece60535036ce41ab1516d4343765076"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "52bfcd6aaac949201c75819ed36a07719e4f916c4c8b0466e119955b95d0e410"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "ba5ac417b4810994e7b0006159aab2d37b29725b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "5a55ca68bf242d89e61fb3f3b9cd460d5d88149997429c36a7f44e675ad86c56"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "c9f4c041b3fa0a73d1f66781dd6fa06642954815"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "556dc9442ac423a42714d494a2c317414aa0959ef2d77a97cb62d4ad395ea0c4"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "117497845c8fb6c6c3f26f0fef466ed0101e724d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "7ad15ce379aac61d1acd84d93b76713026bad87fb61f6e71e8ac65ca7bf60a7e"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "928aa02dccf246333cd9d9e67be7fd24550755a5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "fe4f66f2a9a070f24e9e1e42009efbc87805f0e3416e49b2f885d131d3c4ec1c"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "b3d088530e822242ac167438066f197e96dc54f8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "d3585582c31379495dda8c86ce1cad188ef2b5b7504cba86cf6c55839b09a803"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "96527c7f8ffeae08a88dbee175ef2ad9fb8c9cad"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FEAST.download]]
    sha256 = "0ec611a17f887b4a21efdd502893ae1a0aba11c5fecf70892a28f99ef5673e58"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "46a9d9bf066582ae9fb6f1c548fb5f1c60c710d2"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FEAST.download]]
    sha256 = "0055d3c579515819f45e9fc74a1cf91ee652c9a6e26953d2edd045fd8c7faa01"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "39d346e1ddd3ea892f5c838796740891651fd79d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FEAST.download]]
    sha256 = "d2031f8ff55bd507ba85dcca1aac4068b1f01aae199a3856f08b8d668f6c4e06"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
