[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "8d8012a68d9c31407eee7cc3a4370e41873c8ac2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "52e02a300caa481f4b2473abfa504f19e469def2210dc31ce93dd3e1c1713b56"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "d1ef8bb1c145ed94758f7bf0a3e0bd7678b7f966"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "20e37996dc5e6e3f1628aaba9215ab6b73d829cfe8970197b060acc6be7e2ac4"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "4a6d9958f24a9a2e6dbbde959814e9074a489913"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "0d72c5786562ff2ffea598356e41492b50c627bd4aeaa0f35c73f9f96cb2ccca"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "b2a19336a876d1a12af1a950de64853afecba377"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "1cced546fb3a7e3883f60943045a7f13ca95e380954248041db4f298f7af024d"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "f875e4775203fdc642185b3fbca511ff21882275"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "d2f54befb3edc7eb5f279e80a0f3c4354d78ee2eeb0be58d2930ab7ce303567f"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[FEAST]]
arch = "aarch64"
git-tree-sha1 = "0c0649b88d26443fe4ef447b5be6b87de719a1ca"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "71cc9149665410929667ecc1d94989b382c03a7674e360b6710464392cd4aaac"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "d3820863b8eeb0730dc82b15f2d899d9b39b5c81"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "98401641c2c59779c3f60c65b2e0585678a56adc17712bc947cd3bf0f3bd367f"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "2c004c55d52e86f1f3c9995e1ab03ee16c69f052"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "84df391302c770e1ceb9099a4b5bdf13e937a29ce3a50044188ce9000a1c2adb"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "fdf55583ea39a9e05516ae255140448e7f7e8762"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "ccc5a5a33f1f7ad1a5c71621d5dae5ff46e5a50a53aa88d522dbd51a499c4a5b"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "9d2e6f3561b56ab13d9e9fb8e22526ba4c162e1a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "74b4201a40a3e226d179a47a473bc704d23f951f927b0b2f96d1ec02dc1e8248"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "ae840f77b07d69ed01aef4ed61be7d426da8db5a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "b40362adae6096f80a9f79f693c9b5951d1c1e0ad817536d23af5fc0a435c838"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[FEAST]]
arch = "armv7l"
git-tree-sha1 = "4fa9947a9fb452aafeae7e87c6e59e601f1732cb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "eb9c680d3a6451e92a6560970045c26d26506cb532488c880db82f667c2312f5"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "ba49769b6383d1cedaf3fa9ee6eacd7d78f2003e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "8bdb6d0d3c58d7611d79135e301db0d556268f20c36338aab72e752f088d98de"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-gnu-libgfortran3.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "2ca1c1df404eec3fe9973866e2ac5267bccd4e42"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "f3893f2370b1220d0f12bfd79946b6a4740bea82fe3f3a68b28bd3120196dab9"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "1c7cdb0cc556f6ea5bc9b8fe4b996546a4ea1582"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "1b59f965c87a656fb0ea9cfe29900364ed76e507a4cd80690dc766fcf38cb854"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "914e1cbfcd3fa359e0a040a0dd5df98b86cb4ad9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "877b13eee967aa36e69325f2da4ca824cacce722a790c7bae3ccfc9171868ac9"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-musl-libgfortran3.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "58aa301472c0ddf232f4740eacc4d2fa8559caaa"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "47e8b85b46fe1305b668f8aba9d84d205fbe5956fc588055a14e95427b3723e7"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-musl-libgfortran4.tar.gz"
[[FEAST]]
arch = "i686"
git-tree-sha1 = "505b4d7897dc01d119e96d9d1f29d2de3dbd4666"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "f2c2c525093399916aa6c27fac73d5ad0dd0fbee2e8cdf4185633e51f4b3c327"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "776f594fb0c0814f6e208ed95494ecff6685f7da"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "0c49b92b7525a53559837ddd0474bd5b030f6ade25c78da2bf6ff3caed831d56"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "c1dc6876b82d9d5eb05d05a01ba605d396f9d848"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "114153b2f570e708b9542547388bfb129e7bce68559ed93055dbc66444521ebd"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "112ac36658770a4eecdd5b8c2694f6b858c7c847"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "4f035d55b3477b33edef269f15241b9616fe6ac6c962a5d63453f097d10ddb2e"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "a7ad2a7a4bdb126288f34eea85ed0b795a1ff35a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "54f92f8d4ad2c042af29f4e4a8e7ac889424f44edf07ab874d415500716dfa73"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "34490c0490cee72272ff16cef9b6e6e67cb0ae48"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "4268cdfc9b3a8ed1e061a25fe11db21312a4e195498fa62facdfb5e3f44b736f"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "29573429feda2f64b11df4e6763724df2183edb4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FEAST.download]]
    sha256 = "bbad4013c056a3d63bb1e81cbe3192388d13a4b541d5d664ce64ed8a243affd5"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "0d265a2e4ce2b596e3c1adfef94f3f5e0220b74e"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FEAST.download]]
    sha256 = "0d55ea4f6239649acb1c20c63ab0fcf8e20817b859752c4518703882a88bd52b"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "1006d0126171522f4a5550738c28860874b0d22d"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FEAST.download]]
    sha256 = "59b19fd197aa13a9939916325c74cc295ea792373ef0db2744a598bae991a600"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[FEAST]]
arch = "x86_64"
git-tree-sha1 = "21a7f644fdee531a42404bfa543e3da4d8bfde19"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FEAST.download]]
    sha256 = "bcc7510f39c13282ebfb0b215b46428c56216816a9ca83d2fc750ba81b7de173"
    url = "https://github.com/spacedome/FEAST_jll.jl/releases/download/FEAST-v4.0.0+0/FEAST.v4.0.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
